name: Test Site ey
favicon: null
layout_spectrum: 0.7858382312115282
typography_spectrum: 0.3352442607283592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8229890314396471
  lightness: 0.2897214973345399
  saturation: 0.6594332428649068
  rhythmicContrast: 0.09298589453101158
purpose: []
