name: Test Site ey
favicon: null
layout_spectrum: 0.55815
typography_spectrum: 1
title: An amazine website for life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#850000'
    - '#ffffff'
    - '#cccccc'
    - '#616161'
  brandStrength: 0.875
  lightness: 0.2897214973345399
  saturation: 0.6594332428649068
  rhythmicContrast: 0
purpose: []
