typography_spectrum: 1
color:
  brandColors:
    - '#000000'
    - '#850000'
    - '#ffffff'
    - '#cccccc'
    - '#616161'
  brandStrength: 0.875
  lightness: 0.2897214973345399
  saturation: 0.6594332428649068
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.55815
analytics:
  google: null
  facebook: null
  twitter: null
name: Test Site ey
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: An amazine website for life
description: what is the word?
purpose: []
